"""add order models

Revision ID: 99194c8accfe
Revises: d09713da0daa
Create Date: 2023-09-19 16:16:18.324177

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

from app.models.order import Status

# revision identifiers, used by Alembic.
revision = '99194c8accfe'
down_revision = 'd09713da0daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(Status), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.telegram_chat_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orderitems',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderitems')
    op.drop_table('order')
    # ### end Alembic commands ###
