"""empty message

Revision ID: ce99c2ad2074
Revises: 
Create Date: 2023-09-12 14:44:58.847806

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

from app.models.user import Role

# revision identifiers, used by Alembic.
revision = 'ce99c2ad2074'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('first_name', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=200), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('role', sqlalchemy_utils.types.choice.ChoiceType(Role), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
