"""change cart model

Revision ID: d09713da0daa
Revises: 28e9a2e76068
Create Date: 2023-09-19 14:36:08.136453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09713da0daa'
down_revision = '28e9a2e76068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
